---
apiVersion: v1
kind: Service
metadata:
  name: users-graphql-svc
  labels:
    app: users-graphql
spec:
  ports:
    - name: http
      port: 4101
      targetPort: 4101
  selector:
    app: users-graphql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-graphql
  template:
    metadata:
      labels:
        app: users-graphql
    spec:
      containers:
        - image: zalbiraw/go-api-test-service:v3.3
          imagePullPolicy: IfNotPresent
          name: users-graphql
          command:
            - ./services/graphql/users/server
          ports:
            - containerPort: 4101
          env:
            - name: PORT
              value: "4101"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tyk-otel-collector-opentelemetry-collector.tyk.svc:4318"

