---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: social-media
spec:
  name: Social Media App
  protocol: http
  active: true
  proxy:
    target_url: ""
    listen_path: /social-media
    strip_listen_path: true
  enable_detailed_recording: true
  detailed_tracing: true
  use_keyless: true
  graphql:
    enabled: true
    execution_mode: executionEngine
    schema: |
      type Query {
        user(id: Int!): User
      }

      type User {
        id: Int
        name: String
        email: String
        posts: [Post]
      }

      type Post {
        id: Int
        title: String
        body: String
        comments: [Comment]
      }

      type Comment {
        id: Int
        name: String
        email: String
        body: String
      }

    version: "2"
    playground:
      enabled: true
      path: /playground
    engine:
      field_configs:
        - type_name: Query
          field_name: user
          disable_default_mapping: true
          path: []
        - type_name: User
          field_name: posts
          disable_default_mapping: true
          path: []
        - type_name: Post
          field_name: comments
          disable_default_mapping: true
          path: []
      data_sources:
        - kind: REST
          name: User
          internal: false
          root_fields:
            - type: Query
              fields:
                - user
          config:
            url: http://users-rest-svc.apps.svc:3101/users/{{.arguments.id}}
            method: GET
            body: ""
            headers: {}
        - kind: REST
          name: Posts
          internal: false
          root_fields:
            - type: User
              fields:
                - posts
          config:
            url: http://posts-rest-svc.apps.svc:3102/users/{{.object.id}}/posts
            method: GET
            body: ""
            headers: {}
        - kind: REST
          name: Comments
          internal: false
          root_fields:
            - type: Post
              fields:
                - comments
          config:
            url: http://comments-rest-svc.apps.svc:3103/posts/{{.object.id}}/comments
            method: GET
            body: ""
            headers: {}
