---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: users
spec:
  name: Users
  protocol: http
  active: true
  proxy:
    target_url: http://users-graphql-svc.apps.svc:4101/query
    listen_path: /users
    strip_listen_path: true
  use_keyless: true
  graphql:
    enabled: true
    version: "2"
    execution_mode: proxyOnly
    schema: |
      type Address {
        street: String!
        suite: String!
        city: String!
        zipcode: String!
        geo: GeoLocation!
      }

      type Company {
        name: String!
        catchPhrase: String!
        bs: String!
      }

      type GeoLocation {
        lat: String!
        lng: String!
      }

      type Query {
        user(id: ID!): User!
        users: [User!]!
      }

      type User {
        id: ID!
        name: String!
        username: String!
        email: String!
        address: Address!
        phone: String!
        website: String!
        company: Company!
      }
    playground:
      enabled: true
      path: /playground
