---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-cp-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis-cluster
    targetRevision: v10.2.7
    helm:
      releaseName: tyk-cp-redis
      values: |
        password: "topsecretpassword"
        redis:
          resourcesPreset: "none"
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-cp-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: v15.5.18
    helm:
      releaseName: tyk-cp-storage-postgres
      values: |
        auth:
          database: "storage"
          postgresPassword: "topsecretpassword"
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-cp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.tyk.io/public/helm/charts
    chart: tyk-control-plane
    targetRevision: v2.1.0
    helm:
      releaseName: tyk
      values: |
        global:
          secrets:
            useSecretName: "tyk-cp-conf"
          adminUser: 
            email: "default@example.com"
            password: "topsecretpassword"
          storageType: "postgres"
          postgres:
            host: "tyk-cp-storage-postgres-postgresql.tyk.svc"
            port: 5432
            password: "topsecretpassword"
            database: "storage"
            sslmode: "disable"
          redis:
            addrs:
            - "tyk-cp-redis-redis-cluster.tyk.svc:6379"
            pass: "topsecretpassword"
            enableCluster: true
        tyk-dashboard:
          fullnameOverride: tyk-dashboard
          dashboard:
            image:
              tag: v5.6
            tykApiHost: http://gateway-svc-tyk-gateway.tyk.svc
            extraEnvs:
              - name: TYK_DB_SECURITY_OPENPOLICY_ENABLED
                value: true
              - name: TYK_DB_SECURITY_OPENPOLICY_ENABLEAPI
                value: true
              - name: TYK_DB_SECURITY_OPENPOLICY_DEBUG
                value: true
            extraVolumes:
              - name: opa-rules
                configMap:
                  name: opa-rules
            extraVolumeMounts:
              - name: opa-rules
                mountPath: /opt/tyk-dashboard/schemas/dashboard.rego
                subPath: dashboard.rego
        tyk-gateway:
          gateway:
            image:
              tag: v5.6
            useDashboardAppConfig:
              dashboardConnectionString: http://dashboard-svc-tyk-dashboard.tyk.svc
              policyConnectionString: http://dashboard-svc-tyk-dashboard.tyk.svc:3000
        tyk-mdcb:
            image:
              tag: v2.7
          mdcb:
            useSecretName: "tyk-cp-conf"
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true