---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-dp-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis-cluster
    targetRevision: v10.2.7
    helm:
      releaseName: tyk-dp-redis
      values: |
        password: "topsecretpassword"
        redis:
          resourcesPreset: "none"
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-dp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.tyk.io/public/helm/charts
    chart: tyk-data-plane
    targetRevision: v2.1.0
    helm:
      releaseName: tyk
      values: |
        global:
          secrets:
            useSecretName: "tyk-dp-conf"
          remoteControlPlane:
            useSecretName: "tyk-dp-conf"
            connectionString: "mdcb-svc-tyk-cp-tyk-mdcb.tyk.svc:9091"
            useSSL: false
            sslInsecureSkipVerify: true
          redis:
            addrs:
            - "tyk-dp-redis-redis-cluster.tyk.svc:6379"
            pass: "topsecretpassword"
            enableCluster: true
        tyk-gateway:
          fullnameOverride: tyk-gateway
          gateway:
            image:
              tag: v5.6
            opentelemetry:
              enabled: "true"
              endpoint: "tyk-otel-collector-opentelemetry-collector.tyk.svc.tyk.svc:4317"
        tyk-pump:
          fullnameOverride: tyk-pump
          pump:
            image:
              tag: v1.11
            service:
              enabled: true
            backend:
            - hybrid
            - prometheus
            prometheusPump:
              customMetrics: "[{\"name\": \"tyk_http_requests_total\",\"description\": \"Total of API requests\",\"metric_type\": \"counter\",\"labels\": [\"response_code\",\"api_name\",\"method\",\"api_key\",\"alias\",\"path\"]},{\"name\": \"tyk_http_latency\",\"description\": \"Latency of API requests\",\"metric_type\": \"histogram\",\"labels\": [\"type\",\"response_code\",\"api_name\",\"method\",\"api_key\",\"alias\",\"path\"]}]"
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
