---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-jaeger-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger-operator
    targetRevision: v2.46.2
    helm:
      releaseName: tyk-jaeger-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-jaeger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TykTechnologies/tyk-argicd-demo.git
    targetRevision: HEAD
    path: resources/jaeger
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true