apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-gql-traffic
  namespace: tyk
data:
  load.js: |
    import http from 'k6/http';
    import { sleep, check, fail } from 'k6';
    import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';

    export const options = {
        insecureSkipTLSVerify: true,
        discardResponseBodies: true,
        scenarios: {
            sendSocialMedia: {
                executor: 'constant-vus',
                exec: 'sendSocialMedia',
                vus: 5,
                duration: '2h',
            },
            sendStarWars: {
                executor: 'constant-vus',
                exec: 'sendStarWars',
                vus: 5,
                duration: '2h',
            }
        }
    };
    
    function createKey(username) {
        const params = {
            responseType: 'text',
        };
        
        let payload = {
            client_id: 'keycloak-oauth',
            grant_type: 'password',
            client_secret: 'NoTgoLZpbrr5QvbNDIRIvmZOhe9wI0r0',
            scope: 'openid',
            password: 'topsecretpassword',
            username,
        };
        
        const res = http.post('http://keycloak-service.tyk.svc:7000/realms/keycloak-oauth/protocol/openid-connect/token', payload, params);
        
        check(res, {
            ['Key creation call status is 200']: (r) => r.status === 200,
        }) || fail('Failed to create ' + username + ' key');
        
        return res.json().access_token
    }
    
    export function setup() {
        const admin     = 'admin@example.com',
              developer = 'developer@example.com';

        return [
            createKey(admin),
            createKey(developer),
        ];
    }
    
    export function sendStarWars(keys) {
        var payload;
        var params;
        
        const queries = [
            'query { species(speciesID: ' + randomIntBetween(0, 40) + ') { name language } }',
            'query { planet(planetID: ' + randomIntBetween(0, 60) + ') { name gravity diameter } }',
            'query { person(persontID: ' + randomIntBetween(0, 60) + ') { name homeworld { name } birthYear } }',
        ]
        
        payload = JSON.stringify({ query: queries[randomIntBetween(0, 2)] });
        params = {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': keys[randomIntBetween(0, keys.length - 1)]
            }
        };
        
        http.post('http://gateway-svc-tyk-gateway.tyk.svc:8080/star-wars', payload, params)
        sleep(randomIntBetween(30, 60));
    }
    
    export function sendSocialMedia() {
        var payload;
        var params;
        
        // Runs 0-10, where 0 will return an error
        payload = JSON.stringify({
            query: 'query { user(id: ' + randomIntBetween(0, 10) + ') { name email posts { title body comments { name email body } } } }',
        });
        
        params = {
            headers: {
                'Content-Type': 'application/json',
            }
        };
        
        http.post('http://gateway-svc-tyk-gateway.tyk.svc:8080/social-media', payload, params)
        sleep(randomIntBetween(30, 60));
    }
---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
    name: k6-gql-traffic
    namespace: tyk
spec:
    parallelism: 1
    separate: false
    quiet: "false"
    script:
        configMap:
            name: k6-gql-traffic
            file: load.js
