---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: httpbin
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin-svc.apps.svc:8000
    listen_path: /httpbin
    strip_listen_path: true
  enable_detailed_recording: true
  detailed_tracing: true
  use_keyless: true
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-jwt
spec:
  name: httpbin-jwt
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin-svc.apps.svc:8000
    listen_path: /httpbin-jwt
    strip_listen_path: true
  enable_detailed_recording: true
  detailed_tracing: true
  enable_jwt: true
  jwt_signing_method: rsa
  jwt_source: http://keycloak-service.tyk.svc:7000/realms/keycloak-oauth/protocol/openid-connect/certs
  jwt_identity_base_field: sub
  jwt_policy_field_name: pol
  jwt_default_policies:
    - tyk/no-op
  jwt_scope_claim_name: group
  jwt_scope_to_policy_mapping:
    admins: tyk/httpbin-admins
    developers: tyk/httpbin-developers
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-admins
spec:
  name: httpbin-admins
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: httpbin-jwt
      namespace: tyk
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-developers
spec:
  name: httpbin-developers
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: httpbin-jwt
      namespace: tyk
      versions:
        - Default
      allowed_urls:
        - url: /xml
          methods:
            - GET