---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: no-op
spec:
  name: no-op
  protocol: http
  active: true
  proxy:
    target_url: http://httpbingo.org
    listen_path: /no-op
    strip_listen_path: true
  enable_detailed_recording: true
  detailed_tracing: true
  use_standard_auth: true
  auth_configs:
    authToken:
      auth_header_name: Authorization
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: no-op
spec:
  name: no-op
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: no-op
      namespace: tyk
      versions:
        - Default