apiVersion: v1
kind: ConfigMap
metadata:
  name: no-op
data:
  no-op.json: |-
    {
      "info": {
        "title": "no-op",
        "version": "1.0.0",
        "state": {
          "internal": true
        }
      },
      "openapi": "3.0.3",
      "components": {
        "securitySchemes": {
          "authToken": {
            "type": "apiKey",
            "in": "header",
            "name": "Authorization"
          }
        }
      },
      "security": [
        {
          "authToken": []
        }
      ],
      "paths": {},
      "x-tyk-api-gateway": {
        "info": {
          "name": "no-op",
          "state": {
            "active": true
          }
        },
        "middleware": {
          "global": {
            "trafficLogs": {
              "enabled": true
            }
          }
        },
        "server": {
          "authentication": {
            "enabled": true,
            "securitySchemes": {
              "authToken": {
                "enabled": true
              }
            }
          },
          "detailedActivityLogs": {
            "enabled": true
          },
          "detailedTracing": {
            "enabled": true
          },
          "listenPath": {
            "strip": true,
            "value": "/no-op/"
          }
        },
        "upstream": {
          "url": "http://httpbin-svc.apps.svc:8000"
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: no-op
spec:
  tykOAS:
    configmapRef:
      name: no-op
      keyName: no-op.json
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: no-op
spec:
  name: no-op
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: no-op
      kind: TykOasApiDefinition
      namespace: tyk
      versions:
        - 1.0.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
  keycloak.json: |-
    {
      "info": {
        "title": "keycloak",
        "version": "1.0.0"
      },
      "openapi": "3.0.3",
      "components": {
        "securitySchemes": {
          "jwtAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
          }
        }
      },
      "paths": {},
      "security": [
        {
          "jwtAuth": []
        }
      ],
      "x-tyk-api-gateway": {
        "info": {
          "name": "keycloak",
          "state": {
            "active": true
          }
        },
        "middleware": {
          "global": {
            "contextVariables": {
              "enabled": true
            },
            "trafficLogs": {
              "enabled": true
            }
          }
        },
        "server": {
          "authentication": {
            "enabled": true,
            "securitySchemes": {
              "jwtAuth": {
                "header": {
                  "enabled": true,
                  "name": "Authorization"
                },
                "identityBaseField": "sub",
                "policyFieldName": "pol",
                "enabled": true,
                "defaultPolicies": [
                  "dHlrL25vLW9w"
                ],
                "scopes": {
                  "claimName": "group",
                  "scopeToPolicyMapping": [
                    {
                      "scope": "admins",
                      "policyId": "dHlrL2tleWNsb2FrLWFkbWlucw"
                    },
                    {
                      "scope": "developers",
                      "policyId": "dHlrL2tleWNsb2FrLWRldmVsb3BlcnM"
                    }
                  ]
                },
                "signingMethod": "rsa",
                "source": "http://keycloak-service.tyk.svc:7000/realms/keycloak-oauth/protocol/openid-connect/certs"
              }
            }
          },
          "detailedActivityLogs": {
            "enabled": true
          },
          "detailedTracing": {
            "enabled": true
          },
          "listenPath": {
            "strip": true,
            "value": "/keycloak/"
          }
        },
        "upstream": {
          "url": "http://httpbin-svc.apps.svc:8000"
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: keycloak
spec:
  tykOAS:
    configmapRef:
      name: keycloak
      keyName: keycloak.json
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-admins
spec:
  name: keycloak-admins
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: keycloak
      kind: TykOasApiDefinition
      namespace: tyk
      versions:
        - 1.0.0
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-developers
spec:
  name: keycloak-developers
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: keycloak
      kind: TykOasApiDefinition
      namespace: tyk
      versions:
        - 1.0.0
      allowed_urls:
        - url: /xml
          methods:
            - GET