---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TykTechnologies/tyk-argocd-demo.git
    targetRevision: HEAD
    path: resources/dependencies/apis
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
