---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.tyk.io/public/helm/charts
    chart: tyk-operator
    targetRevision: v1.0.0
    helm:
      releaseName: tyk-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
