apiVersion: v1
kind: Service
metadata:
  name: prometheus-otel-collector-opentelemetry-collector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: tyk-otel-collector
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
  ports:
    - name: prometheus
      port: 9464
      protocol: TCP
      targetPort: 9464
