---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: users
  namespace: tyk
spec:
  tykOAS:
    configmapRef:
      name: users
      keyName: users.json
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: users
  namespace: tyk
spec:
  name: users
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: users
      kind: TykOasApiDefinition
      namespace: tyk
      versions:
        - 1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
  namespace: tyk
  labels:
    app: users
spec:
  ports:
    - name: http
      port: 3101
      targetPort: 3101
  selector:
    app: users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: tyk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - image: zalbiraw/go-api-test-service:v3.3
          imagePullPolicy: IfNotPresent
          name: users
          command:
            - ./services/rest/users/server
          ports:
            - containerPort: 3101
          env:
            - name: PORT
              value: "3101"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tyk-otel-collector-opentelemetry-collector.tyk.svc:4318"
