---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: no-op-oas
  namespace: tyk
spec:
  tykOAS:
    configmapRef:
      name: no-op-oas
      keyName: no-op-oas.json
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: no-op-oas
  namespace: tyk
spec:
  name: no-op-oas
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: no-op-oas
      kind: TykOasApiDefinition
      namespace: tyk
      versions:
        - 1.0.0
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: keycloak
  namespace: tyk
spec:
  tykOAS:
    configmapRef:
      name: keycloak
      keyName: keycloak.json
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-admins
  namespace: tyk
spec:
  name: keycloak-admins
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: keycloak
      kind: TykOasApiDefinition
      namespace: tyk
      versions:
        - 1.0.0
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-developers
  namespace: tyk
spec:
  name: keycloak-developers
  state: active
  active: true
  per: -1
  quota_max: -1
  quota_renewal_rate: -1
  rate: -1
  throttle_interval: -1
  throttle_retry_limit: -1
  access_rights_array:
    - name: keycloak
      kind: TykOasApiDefinition
      namespace: tyk
      versions:
        - 1.0.0
      allowed_urls:
        - url: /xml
          methods:
            - GET